name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Remote ssh command
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ./deployment_scripts/radio-rasclat-web.sh
